## Q1

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

In [6]:
def G_func(a,n,M):
    g = []
    for x in range (2**n):
        g.append((a**x)%M)
    return np.array(g)

In [7]:
def X_func(g, theta,M):
    x = np.zeros(len(g))
    count=0
    for i in range(len(g)):
        if g[i] == theta:
            count+=1
            if count<4 or i>(len(g)-10):
                print(f"|{i}> |{g[i]}>")
            x[i]=1
    print(count)
    count = count**0.5
    x/=(count)
    return x
    

In [8]:
def QFT(a):
    N = len(a)
    omega = np.exp(-2j* np.pi/N)
    f=[]
    for y in range(N):
        fy = 0
        for x in range(N):
            fy+=a[x]*(omega**(y*x))
        f.append(fy)
    f = np.array(f)
    f = abs(f)/sum(abs(f))
    f = np.round(f, 4)
    return f
        

In [2]:
np.exp(-2j* np.pi/8)

(0.7071067811865476-0.7071067811865476j)

In [3]:
np.cos(-2*np.pi/8)

0.7071067811865476

In [4]:
np.sin(-2*np.pi/8)

-0.7071067811865476

In [9]:
def findPeak(arr):
    d = []
    for i in range(1,len(arr)-1):
        if(arr[i]>arr[i-1] and arr[i]>arr[i+1]):
            d.append(i)
    return d

In [10]:
def plot(qft):
    plt.figure(figsize=(10, 20))
    plt.bar(range(len(qft)), qft)
    plt.title('QFT')

    # Display the plot
    plt.show()

In [11]:
def ContiFrac(x):
    k = []
    z = []
    k_tmp = 1
    print(f"\nContinuous Fractorization")
    for i in range(3):
        ki = int(x+0.5)
        k.append(ki)
        z.append(k_tmp*ki+1)
        k_tmp = ki
        zi = math.floor(x)
        print(f"{x} = {zi} +", end = " ")
        x -= zi
        x = 1/x
        print(f"1/{x}")
    z[1]=k[1]
    k[1]=1
    return z,k

In [12]:
def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

In [9]:
M = 65
a = 6
m = 7
n = 14

In [10]:
g = G_func(a,n,M)
g

array([ 1,  6, 36, ...,  6, 36, 21])

In [11]:
theta = 21
X = X_func(g,theta,M)
X

|3> |21>
|15> |21>
|27> |21>
|16383> |21>
1366


array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
       0.02705669])

In [12]:
qft = QFT(X)

In [13]:
d = findPeak(qft)
print(f"d = {d}")

d = [1365, 2731, 4096, 5461, 6827, 8192, 9557, 10923, 12288, 13653, 15019]


In [14]:
sorted_indices = np.argsort(-qft)

# Print the top 10 (index, value) pairs
for i in range(10):
    index = sorted_indices[i]
    value = qft[index]
    print(f"Index: {index}, Value: {value}")

Index: 0, Value: 0.0222
Index: 12288, Value: 0.0222
Index: 4096, Value: 0.0222
Index: 8192, Value: 0.0222
Index: 2731, Value: 0.0183
Index: 5461, Value: 0.0183
Index: 9557, Value: 0.0183
Index: 1365, Value: 0.0183
Index: 13653, Value: 0.0183
Index: 10923, Value: 0.0183


In [15]:
d = 1366
N = 2**14

In [16]:
ContiFrac(d/N)


Continuous Fractorization
0.0833740234375 = 0 + 1/11.994143484626647
11.994143484626647 = 11 + 1/1.0058910162002943
1.0058910162002943 = 1 + 1/169.750000000007


([1, 12, 13], [0, 1, 1])

In [17]:
s = 12

In [18]:
6**6+1

46657

In [19]:
p = gcd(M, a**(s/2)-1)
p

5.0

In [20]:
q = gcd(M, a**(s/2)+1)
q

13.0

## Q2

In [13]:
def extended_euclidean(a, n):
    # Initialize values
    r1, r2 = n, a
    t1, t2 = 1, 0  # t now holds the values previously held by s
    s1, s2 = 0, 1  # s now holds the values previously held by t

    # Print the initial header
#     print(f"{'t':<5} | {'s':<7} | {'r':<7} | {'q':<7}")
#     print(f"{t1:<5} | {s1:<7} | {r1:<7} |")
#     print(f"{t2:<5} | {s2:<7} | {r2:<7} |")

    while r2 != 0:
        q = r1 // r2  # Quotient
        r = r1 - q * r2  # Remainder
        r1, r2 = r2, r
        t = t1 - q * t2
        t1, t2 = t2, t
        s = s1 - q * s2
        s1, s2 = s2, s

        if r2 ==0:
            t=""
            s=""
        # Print s, t, r, q in the required format
        #print(f"{t:<5} | {s:<7} | {r:<7} | {q:<7}")

    # At the end of the loop, r1 is the gcd and s1 is the modular inverse if r1 == 1
    if r1 == 1:
        return s1 % n  # Ensure the inverse is positive
    else:
        return None  # Inverse doesn't exist if gcd(a, n) != 1



In [14]:
x=[1,2,3,5]
y=[5,1,7,4]

In [15]:
q = 7
f = 0
lambda_ = np.zeros((4,4), dtype=int)
f = np.zeros((4), dtype=int)
for X in range(1):
    for i in range(4):
        den = 1
        neu = 1
        for j in range(4):
            if(i==j):
                continue
            den*=(x[i]-x[j])
            neu*=(X-x[j])
        print(f"lambda_{i}({X}) = {neu}/{den}")
        g= gcd(abs(neu),abs(den))
        neu//=g
        den//=g
        if den<0:
            neu *=-1
            den *=-1
        print(f"lambda_{i}({X}) = {neu}/{den}")
        neu= neu% q
        den = extended_euclidean(den, q)
        lambda_[X][i]=(neu*den)%q
        print(f"lambda_{i}({X}) = {neu}*{den} mod {q} = {lambda_[X][i]}")

        f[X] +=y[i]*lambda_[X][i]
    
    f[X]%=q
    print(f"f({X}) = {f[X]%q}")
print(f)

lambda_0(0) = -30/-8
lambda_0(0) = 15/4
lambda_0(0) = 1*2 mod 7 = 2
lambda_1(0) = -15/3
lambda_1(0) = -5/1
lambda_1(0) = 2*1 mod 7 = 2
lambda_2(0) = -10/-4
lambda_2(0) = 5/2
lambda_2(0) = 5*4 mod 7 = 6
lambda_3(0) = -6/24
lambda_3(0) = -1/4
lambda_3(0) = 6*2 mod 7 = 5
f(0) = 4
[4 0 0 0]


## Q4

In [24]:
p = 139
q = 23
g = 6
h = 80
c1s = [112,106,44,129,57,79,55]
c2s = [1,125,52,100,44,77,112]
x = [1,2,3,4]
w = [79,36,77,106]
J=[1,2,4]

In [21]:
def count_c(c1s,p):
    c1 = 1
    for i in range(len(c1s)):
        print(f"{c1} x {c1s[i]} =", end="")
        c1 = c1*c1s[i]
        print(f" {c1} mod {p}", end ="")
        c1 = c1%p
        print(f" = {c1}")

In [25]:
def lambda0(x):
    t = len(x)
    X=0
    lambda_up = np.ones(t)
    lambda_down = np.ones(t)
    for i in range (t):
        for j in range(t):
            if i==j:
                continue
            else:
                lambda_up[i]*=(X-x[j])
                lambda_down[i]*=(x[i]-x[j])
        print(f"lambda_{i}({X}) = {lambda_up[i]} / {lambda_down[i]}")

In [42]:
def square_and_multiply(a, b, n):
    z = 1
    a = a % n
    print(f"{a}^{b}mod{n}")
    print(f"{'b':<2} |{'':<35}| {'z':<5}")
    print(f"{'':<2} |{'':<35}| {z:<5}")
    for i in range(b.bit_length() - 1, -1, -1):
        current_bit = (b >> i) & 1
        if current_bit == 0:
            sentence = f"{z}*{z} mod {n}"
            z = (z * z) % n

        else:
            sentence = f"{z}*{z}*{a} mod {n}"
            z = (z* z * a) % n

        print(f"{current_bit:<2} |{sentence:<35}| {z:<5}")
    return z


In [53]:
def extended_euclidean(a, n):
    # Initialize values
    r1, r2 = n, a
    t1, t2 = 1, 0  # t now holds the values previously held by s
    s1, s2 = 0, 1  # s now holds the values previously held by t

    # Print the initial header
    print(f"{'t':<5} | {'s':<7} | {'r':<7} | {'q':<7}")
    print(f"{t1:<5} | {s1:<7} | {r1:<7} |")
    print(f"{t2:<5} | {s2:<7} | {r2:<7} |")

    while r2 != 0:
        q = r1 // r2  # Quotient
        r = r1 - q * r2  # Remainder
        r1, r2 = r2, r
        t = t1 - q * t2
        t1, t2 = t2, t
        s = s1 - q * s2
        s1, s2 = s2, s

        if r2 ==0:
            t=""
            s=""
        # Print s, t, r, q in the required format
        print(f"{t:<5} | {s:<7} | {r:<7} | {q:<7}")

    # At the end of the loop, r1 is the gcd and s1 is the modular inverse if r1 == 1
    if r1 == 1:
        return s1 % n  # Ensure the inverse is positive
    else:
        return None  # Inverse doesn't exist if gcd(a, n) != 1



In [22]:
c1 = count_c(c1s,p)

1 x 112 = 112 mod 139 = 112
112 x 106 = 11872 mod 139 = 57
57 x 44 = 2508 mod 139 = 6
6 x 129 = 774 mod 139 = 79
79 x 57 = 4503 mod 139 = 55
55 x 79 = 4345 mod 139 = 36
36 x 55 = 1980 mod 139 = 34


In [23]:
c2 = count_c(c2s,p)

1 x 1 = 1 mod 139 = 1
1 x 125 = 125 mod 139 = 125
125 x 52 = 6500 mod 139 = 106
106 x 100 = 10600 mod 139 = 36
36 x 44 = 1584 mod 139 = 55
55 x 77 = 4235 mod 139 = 65
65 x 112 = 7280 mod 139 = 52


In [26]:
lambda0(x)

lambda_0(0) = -24.0 / -6.0
lambda_1(0) = -12.0 / 2.0
lambda_2(0) = -8.0 / -2.0
lambda_3(0) = -6.0 / 6.0


In [178]:
lambda_ = [18,21,8]
w_ = [79,36,106]

In [179]:
for j in range(3):
    square_and_multiply(w_[j],lambda_[j],p)
    print("")

79^18mod139
b  |                                   | z    
   |                                   | 1    
1  |1*1*79 mod 139                     | 79   
0  |79*79 mod 139                      | 125  
0  |125*125 mod 139                    | 57   
1  |57*57*79 mod 139                   | 77   
0  |77*77 mod 139                      | 91   

36^21mod139
b  |                                   | z    
   |                                   | 1    
1  |1*1*36 mod 139                     | 36   
0  |36*36 mod 139                      | 45   
1  |45*45*36 mod 139                   | 64   
0  |64*64 mod 139                      | 65   
1  |65*65*36 mod 139                   | 34   

106^8mod139
b  |                                   | z    
   |                                   | 1    
1  |1*1*106 mod 139                    | 106  
0  |106*106 mod 139                    | 116  
0  |116*116 mod 139                    | 112  
0  |112*112 mod 139                    | 34   



In [180]:
(91*34*34)%139

112

In [183]:
extended_euclidean(6**3, 139)

t     | s       | r       | q      
1     | 0       | 139     |
0     | 1       | 216     |
1     | 0       | 139     | 0      
-1    | 1       | 77      | 1      
2     | -1      | 62      | 1      
-3    | 2       | 15      | 1      
14    | -9      | 2       | 4      
-101  | 65      | 1       | 7      
      |         | 0       | 2      


65

In [182]:
(52*36)%139

65

0
6^0mod139
b  |                                   | z    
   |                                   | 1    
1
6^1mod139
b  |                                   | z    
   |                                   | 1    
1  |1*1*6 mod 139                      | 6    
2
6^2mod139
b  |                                   | z    
   |                                   | 1    
1  |1*1*6 mod 139                      | 6    
0  |6*6 mod 139                        | 36   
3
6^3mod139
b  |                                   | z    
   |                                   | 1    
1  |1*1*6 mod 139                      | 6    
1  |6*6*6 mod 139                      | 77   
4
6^4mod139
b  |                                   | z    
   |                                   | 1    
1  |1*1*6 mod 139                      | 6    
0  |6*6 mod 139                        | 36   
0  |36*36 mod 139                      | 45   
5
6^5mod139
b  |                                   | z    
   |                               

In [56]:
(1*125*52*100*44*77*112)%139

52

In [65]:
(((0-1)*(0-2)*(0-3))/((4-1)*(4-2)*(4-3)))%23

22.0

In [71]:
(1/57)%139

0.017543859649122806

In [168]:
# Define the parameters
modulus = 139
base = 34
exponents = range(0,23)  # Range from -7 to 7

# Function to compute modular exponentiation for negative exponents
def modular_exponentiation(base, exp, mod):
    if exp >= 0:
        return pow(base, exp, mod)
    else:
        # For negative exponents, compute the modular inverse of the positive exponentiation
        positive_result = pow(base, -exp, mod)
        return pow(positive_result, -1, mod)

# Compute the results for all exponents in the range
results = {i: modular_exponentiation(base, i, modulus) for i in exponents}
results


{0: 1,
 1: 34,
 2: 44,
 3: 106,
 4: 129,
 5: 77,
 6: 116,
 7: 52,
 8: 100,
 9: 64,
 10: 91,
 11: 36,
 12: 112,
 13: 55,
 14: 63,
 15: 57,
 16: 131,
 17: 6,
 18: 65,
 19: 125,
 20: 80,
 21: 79,
 22: 45}

In [170]:
(-2*-3*-4)/(-1*-2*-3)

4.0

In [171]:
(-1*-3*-4)/(1*1*2)

-6.0

In [173]:
64%23

18

In [174]:
-1*-4

4

In [175]:
1*-2

-2

In [176]:
-2%23

21

In [177]:
((79**18)*(36**21)*(106**8))%139

112